library(data.table)
hhpc<-fread("grep ^[12]/2/2007 household_power_consumption.txt")

datetime<-strptime(paste(hhpc$V1,hhpc$V2),"%d/%m/%Y %H:%M:%S")
png( "plot4.png", width=480, height= 480)
par(mfrow=c(2,2))
plot(datetime, hhpc$V3, type='l', ylab="Global Active Power(kilowatts)")
plot(datetime, hhpc$V4, type='l', ylab="Voltage")
plot(datetime, hhpc$V7, type = "l", ylab="Energy sub metering")
points(datetime, hhpc$V8, type = "l", col="red")
points(datetime, hhpc$V9,  type = "l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1, col=c("black","red","blue"))
plot(datetime, hhpc$V5, type='l', ylab="Global Reactive Power(kilowatts)")
dev.off()